# Homework Assignment #3
BAX 423 | Dane Hamlett

## Assignment I: BoW and TF-IDF

### Part I

#### Use Amazon book reviews (text documents) dataset (small dataset with 10 reviews).

In [35]:
# Import Libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cross_validation import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

# Import Data & Preview Results
df = pd.read_csv("https://raw.githubusercontent.com/danehamlett/UC_Davis/master/BAX_443/Small-Book%20Reviews%20from%20Amazon.csv", 
                sep=",", names=['Rating','Review'])
df.head()

Rating                                             Review
0       2  Ok~ but I think the Keirsey Temperment Test is...
1       2  Repellent Sale of Conservativism  The fatalist...
2       1  I had a bad feeling about this!  And I was rig...
3       2  Lost Credability, QUICKLY!!  I admit, I haven'...
4       2  Poorly written  I tried reading this book but ...

### Part II

#### Use Bag of Words (BoW) and TF-IDF (CountVectorizer and TfidfVectorizer in scikit-learn).

##### Bag of Words (BoW)

In [36]:
# Create a Corpus
corpus = df['Review'].tolist()

# Fitting the CountVectorizer In Order To:
#  1) Tokenize
#  2) Build the Vocabulary
vect = CountVectorizer()

# Fit the Corpus and Assign List Indices
vect.fit(corpus)

# Determine the Size of the Corpus
print(str(len(vect.vocabulary_)) + ' elements in the Corpus.' + '\n')

# Print the Corpus
print(vect.vocabulary_)

904 elements in the Corpus.

{'ok': 552, 'but': 116, 'think': 792, 'the': 782, 'keirsey': 436, 'temperment': 774, 'test': 777, 'is': 417, 'more': 508, 'accurate': 16, 'and': 47, 'cheaper': 135, 'this': 794, 'book': 108, 'has': 352, 'its': 425, 'good': 335, 'points': 593, 'if': 386, 'anything': 54, 'it': 424, 'helps': 361, 'you': 899, 'put': 623, 'into': 410, 'words': 884, 'what': 862, 'want': 847, 'from': 318, 'supervisor': 753, 'not': 540, 'very': 840, 'online': 556, 'does': 217, 'account': 15, 'for': 303, 'difference': 205, 'between': 98, 'when': 863, 'of': 549, 'their': 783, 'options': 560, 'are': 58, 'both': 110, 'exactly': 257, 'like': 462, 'or': 561, 'they': 789, 'don': 223, 'describe': 195, 'at': 65, 'all': 33, 'messes': 496, 'up': 833, 'results': 667, 'did': 203, 'me': 490, 'well': 860, 'am': 40, 'just': 433, 'in': 392, 'denial': 192, 'have': 355, 'taken': 765, 'lot': 472, 'personality': 586, 'type': 821, 'tests': 778, 'sorter': 716, 'pretty': 607, 'idea': 383, 'my': 517, 'stre

In [37]:
# Create a Bag of Words Representation of the Data in a Document-Term Matrix
bag_of_words = vect.transform(corpus)

# Preview the Matrix
print(bag_of_words.toarray())

[[1 0 0 ... 3 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [38]:
# Define the Feature Names
feature_names = vect.get_feature_names()

# Query the Document-Term Matrix to Identify the Index of a Sample Word
print(vect.vocabulary_.get("sale"))

# Query the Document-Term Matrix to Identify the Sample Word of an Index
print(feature_names[681])

681
sale


In [39]:
# Confirm Number of Features
number_of_features = len(feature_names)
print(str(number_of_features) + ' features')

904 features


##### TF-IDF (Term Frequency - Inverse Document Frequency)

In [40]:
# Fitting the CountVectorizer In Order To:
#  1) Tokenize
#  2) Build the Vocabulary
tfidf_vect = TfidfVectorizer()

# Fit the Corpus and Assign List Indices
tfidf_vect.fit(corpus)

# Determine the Size of the Corpus
print(str(len(tfidf_vect.vocabulary_)) + ' elements in the Corpus.' + '\n')

# Print the Corpus
print(tfidf_vect.vocabulary_)

904 elements in the Corpus.

{'ok': 552, 'but': 116, 'think': 792, 'the': 782, 'keirsey': 436, 'temperment': 774, 'test': 777, 'is': 417, 'more': 508, 'accurate': 16, 'and': 47, 'cheaper': 135, 'this': 794, 'book': 108, 'has': 352, 'its': 425, 'good': 335, 'points': 593, 'if': 386, 'anything': 54, 'it': 424, 'helps': 361, 'you': 899, 'put': 623, 'into': 410, 'words': 884, 'what': 862, 'want': 847, 'from': 318, 'supervisor': 753, 'not': 540, 'very': 840, 'online': 556, 'does': 217, 'account': 15, 'for': 303, 'difference': 205, 'between': 98, 'when': 863, 'of': 549, 'their': 783, 'options': 560, 'are': 58, 'both': 110, 'exactly': 257, 'like': 462, 'or': 561, 'they': 789, 'don': 223, 'describe': 195, 'at': 65, 'all': 33, 'messes': 496, 'up': 833, 'results': 667, 'did': 203, 'me': 490, 'well': 860, 'am': 40, 'just': 433, 'in': 392, 'denial': 192, 'have': 355, 'taken': 765, 'lot': 472, 'personality': 586, 'type': 821, 'tests': 778, 'sorter': 716, 'pretty': 607, 'idea': 383, 'my': 517, 'stre

In [41]:
# Create a Bag of Words Representation of the Data in a Document-Term Matrix
tfidf = tfidf_vect.transform(corpus)

# Preview the Matrix
print(tfidf.toarray())

[[0.06143829 0.         0.         ... 0.15668449 0.         0.        ]
 [0.         0.02325564 0.02325564 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.08745341]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.05937969 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:1089: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [42]:
# Define the Feature Names
tfidf_feature_names = tfidf_vect.get_feature_names()

# Query the Document-Term Matrix to Identify the Index of a Sample Word
print(tfidf_vect.vocabulary_.get("think"))

# Query the Document-Term Matrix to Identify the Sample Word of an Index
print(tfidf_feature_names[792])

792
think


In [43]:
# Confirm Number of Features
tfidf_number_of_features = len(tfidf_feature_names)
print(str(tfidf_number_of_features) + ' features.')

904 features.


### Part III

#### Write Python program to create and print vocabulary and document-term matrix (vectorized representation).

< See Cells Above for BoW and TF-IDF Scripts>

### Part IV

#### Try unigram and bigram parameters and observe their effect on number of features.

In [44]:
# Define Ngram Range
ngram_start = 1
ngram_end = 5

# Define Ngram-baed Vectorizer & Fit the Model
ngram_vect = CountVectorizer(ngram_range=(ngram_start, ngram_end))
ngram_vect.fit(corpus)
ngram_bag_of_words = ngram_vect.transform(corpus)
ngram_feature_names = ngram_vect.get_feature_names()

# Print the Results
ngram_number_of_features = len(ngram_feature_names)
print(str(ngram_number_of_features) + ' features when capturing words with a length between ' + str(ngram_start)
     + ' and ' + str(ngram_end) + '.' + '\n')
print('The number of features will increase as the ngram range widens.' + '\n')

# Sample a Value
print(str(ngram_vect.vocabulary_.get("quite painful when left alone")) + '\n')

# Confirm Index
print(ngram_feature_names[6030] + '\n')

# List the Full Vocabulary
print(ngram_vect.vocabulary_)

9034 features when capturing words with a length between 1 and 5.

The number of features will increase as the ngram range widens.

6030

quite painful when left alone

{'ok': 5464, 'but': 1365, 'think': 7674, 'the': 7182, 'keirsey': 4346, 'temperment': 7053, 'test': 7076, 'is': 3959, 'more': 4883, 'accurate': 95, 'and': 398, 'cheaper': 1606, 'this': 7688, 'book': 1253, 'has': 3087, 'its': 4244, 'good': 2960, 'points': 5811, 'if': 3589, 'anything': 715, 'it': 4141, 'helps': 3318, 'you': 8957, 'put': 5985, 'into': 3924, 'words': 8805, 'what': 8581, 'want': 8375, 'from': 2826, 'supervisor': 6932, 'not': 5088, 'very': 8306, 'online': 5518, 'does': 2101, 'account': 90, 'for': 2634, 'difference': 2034, 'between': 1195, 'when': 8610, 'of': 5195, 'their': 7578, 'options': 5541, 'are': 739, 'both': 1331, 'exactly': 2365, 'like': 4572, 'or': 5546, 'they': 7640, 'don': 2137, 'describe': 1977, 'at': 872, 'all': 214, 'messes': 4798, 'up': 8248, 'results': 6263, 'did': 2020, 'me': 4756, 'well': 852

## Assignment II: Speech-to-Text Cognitive Service Exercise

### Part I

#### Assess the speech-to-text services from the primary vendors:

- <a href="https://docs.microsoft.com/en-us/azure/cognitive-services/speech/home" target="_blank">Microsoft</a>
    - Microsoft has a speech API available that allows for voice command control, user dialog using natural speech conversation, and speech transcription and dictation.
    - The API supports 'speech to text', which converts human speech to text that can be used as input or commands to control an application, and 'text to speech' which converts text to audio streams that can be played back to the user of an application.
    - Microsoft also has a speech recognition API, which allows the transcription of audio into text in real time, and supports the reception of intermediate results of the words that have been recognized so far.
    - The API supports many spoken languages in multiple dialects.
    - In addition, the API also supports capitalization and punctuation, masking profanity, and text normalization.
<p><br></p>
- <a href="https://aws.amazon.com/transcribe/" target="_blank">Amazon</a>
    - Amazon offers a speech recognition service and API called Amazon Transcribe, which allows you to analyze audio files stored in Amazon S3, and return a text file of the speech transcription.
    - The service can transcribe audio, video, and phone calls.
    - You can expand the vocabulary available with the service, with custom words and phrases.
    - The service has the ability to determine distinct speakers.
    - The service applies punctuation, to ensure that reading the transcript can be used without further editing.
<p><br></p>
- <a href="https://cloud.google.com/speech-to-text/" target="_blank">Google</a>
    - Google's speech to text service can process real-time streaming audio, or pre-recorded content.
    - The service recognizes 120 languages and variants.
    - The service returns text immediately, as the speech is being transcribed.
    - Neural network algorithms allow the accuracy of the speech recognition to improve over time.
<p><br></p>
- <a href="https://www.ibm.com/watson/services/speech-to-text/" target="_blank">IBM</a>
    - IBM's speech to text service transcribes speech from multiple languages into a JSON response, supporting two sampling rates: broadband, and narrowband.
    - Transcribes audio from 7 languages.
    - Customizable speech engine, allowing users to incorporate critical content.
    - You can pass as much as 100GB of audio to the service, as a continuous stream of data.